User.create :id => 1,
            :username => "asolkar",
            :email => "mahesh@mahesha.com",
            :fullname => "Mahesh Asolkar",
            :password => 'sunday'
User.create :id => 2,
            :username => "junkshun",
            :email => "junkshun@gmail.com",
            :fullname => "Junk Shun",
            :password => 'sunday'
